name: Concourency
run-name: Deploy to (${{ inputs.env}})
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        type: environment
        required: true
concurrency:
  group: ${{ github.event.inputs.env}}
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps: 
      - run: sleep 20
