name: Docker
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:26-alpine3.22
      ports:
        - 80
      env:
        NODE_ENV: production
    steps:
      - name: check node version
        run: |
          node -v
          cat /etc/os-release
      - name: log env
        run: echo $NODE_ENV   
      - name: creat a file
        run: echo 'Hello from docker container' > hello.txt       
      - name: container in step
        uses: docker://node:18-alpine3.15
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+5
      - name: log ver
        uses: docker://node:18-alpine3.15
        with:
          args: -v
      - name: Show file content
        uses: docker://node:18-alpine3.15
        with:
          entrypoint: cat
          args: hello.txt    
      - uses: actions/checkout@v3
      - name: run script in container
        uses: docker://node:18-alpine3.15
        with:
          entrypoint: ./script.sh
          args: "Hello script"