name: Docker
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 26-alpine3.22
      ports:
        - 80
      env:
        NODE_ENV: production
    steps:
      - name: check node version
        run: |
          node -v
          cat /etc/os-release
      - name: log env
        run: echo $NODE_ENV          
