name: Dynamic jobs matrix
on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system'
        default: "ubuntu-latest,windows-latest"
        type: string
      node-version:
        description: 'Node versions'
        default: "14, 15, 16"
        type: string 
jobs:
  Pre_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix_script: "${{ steps.pre-matrix.outputs.result }}"
    steps:
      - uses: actions/github-script@v6
        id: pre-matrix
        with:
          script: "return {os: context.payload.inputs['os'].split(','), 'node-version': context.payload.inputs['node-version'].split(',')}"
          result-encoding: json
      - run: echo "${{ steps.pre-matrix.outputs.result}}"   
      - run: echo "setOutput=value" >> $GITHUB_OUTPUT
        id: step-1
      - run: echo "setOutput=value1" >> $GITHUB_OUTPUT
        id: step-2
      - run: |
          echo "${{ steps.step-1.outputs.setOutput}}"  
          echo "${{ steps.step-2.outputs.setOutput}}"  
  #node_matrix: 
    #needs: Pre_matrix     
   # strategy:
   #   matrix:
   #     os: ${{ fromJson(needs.Pre_matrix.outputs.matrix_script).os }}
   #     node-version: ${{fromJson(needs.Pre_matrix.outputs.matrix_script).node-version}}
   # runs-on: ${{ matrix.os }}         
   # steps:
   #   - name: check default node
   #     run: node -v
   #   - name: setup node
   #     uses: actions/setup-node@v3
   #     with:
   #       node-version: ${{ matrix.node-version }}
   #   - name: check node version
  #      run: node -v */