name: First Flow
on: [push]

jobs:
    build:
        runs-on:ubuntu-latest
        steps:
            - name: run cmd
                run: echo "Hello world"
            - name: multiple cmd
                run: |
                    npm -v
                    node -v
