name: Complete-workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run cmd
        run: echo "Hello new World!"
      - name: run multiple cmd
        run: |
          npm -v
          node -v  
  build2:
    runs-on: macos-latest
    steps:
      - name: mac cmd
        run: sw_vers
  dependent_job:
    needs: [build, build2]
    runs-on: windows-latest
    steps:
      - name: windows cmds
        run: Write-Output "Windows String"
      - name: error cmd_test
        run: doesnotexist                