name: Multiple jobs matrix
on: [push]
jobs:
  node_matrix:
    continue-on-error: false    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
        include:
          - experimental: false
          - os: ubuntu-latest
            node-version: 15          
          - os: ubuntu-latest
            node-version: 16
            experimental: true
          - os: ubuntu-latest
            node-version: 17  
        exclude:
          - os: ubuntu-latest
            node-version: 14          
      max-parallel: 3
      fail-fast: false 
    runs-on: '${{ matrix.os }}'             
    steps:
      - if: matrix.experimental == true
        run: exit 1
      - name: check default node
        run: node -v
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: check node version
        run: node -v
      - run: echo '${{ toJson(matrix)}}'