name: Reusable Workflow
on:
  workflow_call:
    inputs:
      name:
        description: "This is python"
        type: string
        default: "santhosh"
        required: false

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -a
  log-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Display Github Context
        run: echo '${{ toJSON(github) }}'
      - name: Display name input
        run: echo ${{ inputs.name }}