name: Test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: list files before
        run: ls -a
      - name: checkout
        uses: actions/checkout@v3
      - name: list files after
        run: ls -a