name: workflow run
on:
  workflow_run:
    workflows: ["Complete-workflow"]
    types: [completed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: content
        run: echo "It is triggered bcoz (Complete-workflow) was completed"                